name: Update Starred Repos

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Create _data directory
        run: mkdir -p _data
      - name: Fetch and save starred repos
        run: |
          token=$GITHUB_TOKEN
          username="NukeTurtle"
          url="https://api.github.com/users/${username}/starred"
          starred_repos=$(curl -sS --request GET --header "Authorization: token $token" $url | jq '[.[] | { name: .full_name, url: .html_url }]')
          echo "$starred_repos" > _data/starred_repos.json
        env:
          GITHUB_TOKEN: ${{ secrets.API_KEY }}

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add _data/starred_repos.json
          git commit -m 'Update _data folder with starred repos'

      - name: Push changes
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/myUser/myRepo.git
          git push --force --set-upstream origin main
        working-directory: ${{ github.workspace }}/_data


# - name: Configure Git
#         run: |
#           set -e
#           git init
#           git credential-cache exit
#           git config --global url.https://${{ secrets.PAT_TOKEN }}@github.com/.insteadOf https://github.com/
#           git config --global user.name 'NukeTurtle'
#           git config --global user.email 'stiglic.elvis@gmail.com'
#           git remote add origin https://github.com/NukeTurtle/stiglicelvis.com.git
#           git remote set-url origin https://github.com/NukeTurtle/stiglicelvis.com.git
#           # git checkout -b main
#           git pull origin main
      
#       - name: Fetch and save starred repos
#         run: |
#           set -e
#           # token=${{ secrets.API_KEY }}
#           url="https://api.github.com/users/NukeTurtle/starred"
#           starred_repos=$(curl -sS --request GET --url "$url" | jq '[.[] | { name: .full_name, url: .url }]')
#           # starred_repos=$(curl -sS --request GET --header "PRIVATE-TOKEN: $GITHUB_TOKEN" $url | jq '[.[] | { name: .full_name, url: .url }]')
#           # curl -sS --request GET --header "PRIVATE-TOKEN: $GIT_TOKEN" "$GIT_API/groups/1079" | jq -r ".description"
#           echo "$starred_repos" > _data/starred_repos.json
#           echo "Starred repositories fetched and saved successfully."
      
#       - name: Commit changes
#         run: |
#           set -e
#           git add .
#           git commit -m 'Update _data folder with starred repos'
#         working-directory: ${{ github.workspace }}/_data
      
#       - name: Push changes
#         run: |
#           set -e
#           git push --force --set-upstream origin main
#         working-directory: ${{ github.workspace }}/_data